sudo: required
services:
- docker
language: node_js
node_js:
- '8'
before_script:
- npm test
script:
- sh .travis/dockerhub/build.sh
- sh .travis/heroku/build.sh
after_success:
- npm run infra
after_script:
- sh .travis/dockerhub/push.sh
- sh .travis/heroku/push.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=menu
  - HEROKU_APP_NAME=iosr2017menu
  - secure: r0qgeuU+iIuAmdRw5fVHHQjVbVoUPQ5hylNPosqNBXMwUSkoirfSUIIkckvMy2/Q8Od8zi7kxkiS6cVICdX6R630RA5zShRXP8J0OdF7l9Ohf2RAg/gbMSIF9KPR6+I5lt1aH38ziuPWPiu4idH5rXIqyX7WxblXFzLjxqGqE0U86Nsi4R0qLYtrT9iOnyy7OGdXCnirWEOPLMDPV61zNpBA/MBsh2NfJdGHmutWR+M21dvBeXRijiW9FGpwGQO9e/IKSU4OFRbmi4PyAIUuW96um70unXMPCvh5SFKtBTOMIVCExyKKt2W0oj0yU/K+JE5J9mzIYjdMs1pNXkTfhcb8d/GpmjnzJIuwpvNGAO6FOA+LSpopDlhB35RmzNxuwcuWuRWdlWI6q90XMGG8QqnmYB7CDo3fQX9Z1wZNQMx9GcOhvkr4X3bq9v/00VnWFtqKMMpWGHisQktkWcWXu3iMdzyOpym7cTQfE5Z2eDg2dVJGYJay9krz8mS7ccf3n3LFZx38zYyQK+IBL+rPbFAPnIHwBx78L8RRXyMwLXwPbbntq0PB/P48yVhAhAU/xOwniPSd8adHVf5ro+PCgCKoJwzPOmdzp4t9LWrcaTucAKe2EdsuO4jX6SCKzx8wyPJLmifmYOtGitRsyFmdOe7yXn0D+FqPPBms2xNJyi8=
  - secure: TKeThXsXb5sX8OlJSQAm/hTIqs55vIgki+ZTafJaGV4Ko6B7IFhww9nMqotr2j3JPcTnTE0JedUqSx/xwxUUm8etTO1za2zNUY3AusuZ/p3gfmK1Whd7V+zohWQww83trYAKK43tVA80vF9AXjH06Ai4/jIjiGAWNtMrY0uAMXrsXi3XNquzMbeGp5ldlrqlD7jvrL8QaubJNhyA9Vu7pZez59ibtLoX07EbMgeFlYU8vsFfhnamTNgqcU6dQHuTpMWeeSsjRLH4qIQQEpw4uB7UFURA+qXnJOR5acK6iOLdSf0jgYnHg2l4X1AeytQrsMKqWPL8SNvlpU+Qt5Kr4HsaZyVzVydo5PhGNqag/gHztVVow5KZLg/3Mzn2L7WZu3D5r14O/AsDErUcND0YZc7BizEft5B/W5gn9wpMbW35ZtWeGc0uInY7yn8Fve42kQHByyqeJTh+Xf1sHdbiLAZpDGOcJyoAyGD+Z3C6OCwvd05A5pJG7StYOcMBqinUnHFV85HHt5fNiR8Ebu1T6eaAVCIqQ4zFu5/bYDry+P15Skqb4kfoaax3UlhNpM0sV0g6ZCyhrVP7syZfNs9X53YxcjE+i02uDCNP1C7XqYGCmgD7/k7WGlflN3mWvlXozM9WOrTqqHt7sFMTvdQlxNtbHeB0ze3N2TikdGRCBjc=
