sudo: required
git:
  depth: false
services:
- docker
language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_1808dd8c2bbc_key -iv $encrypted_1808dd8c2bbc_iv -in .netrc.enc -out .netrc -d
- git clone https://github.com/pkoniu/iosr-2017-deployment.git
- sh iosr-2017-deployment/before_install.sh
install:
- npm install
before_script:
- npm test
script:
- sh iosr-2017-deployment/script.sh
after_success:
- sh iosr-2017-deployment/after_success.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=menu
  - HEROKU_APP_NAME=iosr2017menu
  - secure: K7SCTZhL8gkhQxJPYfyK5LsECyH9HoVlJ/x+G1vSF2QRe0L/AydaCPePGr/aLIwJ2pmG3iD3CI6wPwXpx5NcrmM8sS7bjHurEx/sDEHfkv/5L+cCbx12fPpfKM6P7iPqv41TJkVa04iK4nk/X1+CTphRQlxAD/psagqm5m454S5BFGVXaCTiSHJySfaKZtndp+GsBb4CHrff50PzV/KsEafbLPjOsClwvz5jaDid4j0mkKgMDlxuwtY70JztW8/PTBIw6YC650TBOoq+ttMWQkRq0gjmZi3xzNofOOQ7bY7SM65eoAswT8TtZcu24g3QIrUUzAr6igjyXlXPm2P/6a3o9a6FKmZGB20KL5E75Y5wzBG5bXHYzOezCo41dj5Ag62TYBW7zWD91Doqbbd4itaYJqGUKyqMEFK5F6g4wIpJHlnQKsd1VEhYICw5uJ3liR0p6JENF+gkbBqhxAHnzrBNnwzx1zlcn7ynrKneos1VJ70z8JVJhw9xzuoHYCAw55oxOJZMBJzzPRwVGnt6zJZLyl+S/tpypw/ELe+Yk1nAFZVVDGzhmXP6QCd261heNEUFzW9QAsm75aM8klYxfpfsacOLyebn2jC5Ch/V24qu3lGAbrbn0MijVF+ESPsTdiJ5O5/yXyOJqTZzN1plQ0NqUomzrHHtpsRsbJnszjY=
  - secure: fvWGML+XPxCdg4GO1W2YwCZdhr2V2H2PbioFgsfZ8Fu6Yd35fzz/pPDXIRrNi11Ooj6R2Ec0PCNTez2N19dt28ErH74bJJRXSaltIFyVDKN/2oDJrMWgZeoNW+v++gxeYG60VK60wDh6ZeFYWx5GSQey1Y+StJFbPRgvTm9yEaRTFrlEyFvjiU4XXdJyNchq9iXvtPp5LKbFv2Zw2PZBgR2eUhLxkDsTHCGzEPin/s9BNGPUd1xhq8eMD28/uUT4RHl9BYoKa9gshhhYWHQklFkDZJ1ft/lPISGipIc0pFDIQNQLzP55PA7WL4ndC1KeJNO2aj6rPETwYbvbFnHugS11Bqyj7TKhW0H4ZYNRyqtoDBh9IMwYBVfjKeALidX+OTkfcW9BKsvFKe/TOCM8+Z9S6++qfAYTYNiNQ0hPmyXSxktQTzgUd7WU5YSIJNopk2/NjfZbnguppCexcLHTMvxOqhbFev6dkPfyXlwAi7T3k8DgjWKysqi7uu2vYWAKsEnGqD180Pz3lDWGvTXN7kG6VthdVv/87VEbJx7ecyPj4OEDF6MDx/dKJGNyCPTDBDL5/hJ4yIallzBsjxI5bunvTHdA1yuU0bMEBoKDVkuzETcdHrP7HQySBZPiMqP6S/UJRMuwfZ3cRewjlRmXFtHO1kBE0jtjJvC1WS1+4cw=
